
NAME = unnecessary_violence
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
OBJS_FOLDER = ./obj/
SRC = main.cpp HumanA.cpp HumanB.cpp Weapon.cpp
OBJS = $(addprefix $(OBJS_FOLDER), $(SRC:.cpp=.o))

all: $(OBJS_FOLDER) $(NAME)

$(OBJS_FOLDER):
	@mkdir -p $(OBJS_FOLDER)

$(NAME): $(OBJS)
	@$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

$(OBJS_FOLDER)%.o: %.cpp
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@rm -rf $(OBJS_FOLDER)

fclean: clean
	@rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re